<?php

/**
 * BaseType
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property string $name
 * @property Doctrine_Collection $PostTypeAlias
 * 
 * @method string              getName()          Returns the current record's "name" value
 * @method Doctrine_Collection getPostTypeAlias() Returns the current record's "PostTypeAlias" collection
 * @method Type                setName()          Sets the current record's "name" value
 * @method Type                setPostTypeAlias() Sets the current record's "PostTypeAlias" collection
 * 
 * @package    test
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseType extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('type');
        $this->hasColumn('name', 'string', 255, array(
             'type' => 'string',
             'unique' => true,
             'notnull' => true,
             'length' => 255,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasMany('Post as PostTypeAlias', array(
             'refClass' => 'PostType',
             'local' => 'type_id',
             'foreign' => 'post_id'));
    }
}