<?php

/**
 * BasePostType
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $post_id
 * @property integer $type_id
 * 
 * @method integer  getPostId()  Returns the current record's "post_id" value
 * @method integer  getTypeId()  Returns the current record's "type_id" value
 * @method PostType setPostId()  Sets the current record's "post_id" value
 * @method PostType setTypeId()  Sets the current record's "type_id" value
 * 
 * @package    test
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BasePostType extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('post_type');
        $this->hasColumn('post_id', 'integer', null, array(
             'type' => 'integer',
             'primary' => true,
             ));
        $this->hasColumn('type_id', 'integer', null, array(
             'type' => 'integer',
             'primary' => true,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        
    }
}