default:
  http_metas:
    content-type: text/html

  metas:
    title:        Manage types
    description:  type

  stylesheets:    []

  javascripts:    []

  has_layout:     true
  layout:         layout

indexSuccess:
  metas:
    title: Manage types list
editSuccess:
  metas:
    title: Editing type
createSuccess:
  metas:
    title: Creating type
