default:
  http_metas:
    content-type: text/html

  metas:
    title:        Manage queries
    description:  query

  stylesheets:    []

  javascripts:    []

  has_layout:     true
  layout:         layout

indexSuccess:
  metas:
    title: Manage queries list
editSuccess:
  metas:
    title: Editing query
createSuccess:
  metas:
    title: Creating query
