<?php

/**
 * PostTable
 *
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class PostTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object PostTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Post');
    }
    public function retrieveAdminPostList(Doctrine_Query $q) {
      $rootAlias = $q->getRootAlias();
      $q->leftJoin($rootAlias . '.JobeetCategory c');
      return $q;
    }
}
