<?php

/**
 * Query
 *
 * This class has been auto-generated by the Doctrine ORM Framework
 *
 * @package    test
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
class Query extends BaseQuery
{
  static public function getQueries($param = []){
    $query = Doctrine_Query::create()->select('q.*')->from('Query q');
    foreach($param as $key=>$value){
      $query = $query->addWhere('q.'.$key.'=?',$value);
    }
    return $query->execute()->toArray();
  }
  static public function generateToken(){
    $chars = 'abdefhiknrstyzABDEFGHKNQRSTYZ23456789';
    $string = '';
    for ($i = sfConfig::get('app_token_length'); $i--;){
      $string .= substr($chars, rand(1, strlen($chars)) - 1, 1);
    }
    return $string;
  }
  static public function setStatuses($tokens, $status) {
    $q = Doctrine_Query::create()->from('Query q')->whereIn('q.token', $tokens);
    foreach ($q->execute() as $query) {
      $query->status = $status;
      $query->save();
    }
    return $q;
  }
}
