<?php

/**
 * Type
 *
 * This class has been auto-generated by the Doctrine ORM Framework
 *
 * @package    test
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
class Type extends BaseType
{
  static public function getTypes($param = []){
    $query = Doctrine_Query::create()->select('t.*')->from('Type t');
    foreach($param as $key=>$value){
      $query = $query->addWhere('t.'.$key.'=?',$value);
    }
    return $query->execute()->toArray();
  }
  public function getPostsCount(){
    $query = Doctrine_Query::create()->select('pt.*')->from('PostType pt')->addWhere('post_id='.$this->getId())->count();
    return $query;
  }
}
