default:
  http_metas:
    content-type: text/html

  metas:
    title:        Manage comments
    description:  comments

  stylesheets:    []

  javascripts:    []

  has_layout:     true
  layout:         layout

indexSuccess:
  metas:
    title: Manage comment list
editSuccess:
  metas:
    title: Editing comment
createSuccess:
  metas:
    title: Creating comment
