default:
  http_metas:
    content-type: text/html

  metas:
    title:        Manage posts
    description:  post

  stylesheets:    []

  javascripts:    []

  has_layout:     true
  layout:         layout

indexSuccess:
  metas:
    title: Manage post list
editSuccess:
  metas:
    title: Editing post
createSuccess:
  metas:
    title: Creating post
