<?php
// auto-generated by sfDatabaseConfigHandler
// date: 2017/03/17 12:51:49

return array(
'doctrine' => new sfDoctrineDatabase(array (
  'dsn' => 'mysql:host=localhost;dbname=posts',
  'username' => 'root',
  'password' => 'toor',
  'name' => 'doctrine',
)),);
