<?php
// auto-generated by sfDefineEnvironmentConfigHandler
// date: 2017/03/17 12:51:49
sfConfig::add(array(
  'app_token_length' => 10,
  'app_posts_list_length' => 2,
  'app_comments_list_length' => 3,
));
